name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: build
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: true
